version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Optional: For live code reload during development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
